catalogs:
  clickhouse:
    enabled: false
    host: localhost
    password: ''
    port: '8123'
    user: default
  db2:
    database: sample
    enabled: false
    host: localhost
    password: ''
    port: '50000'
    user: db2inst1
  delta-lake:
    enabled: false
    metastore_host: localhost
    metastore_port: '9083'
  elasticsearch:
    enabled: false
    host: localhost
    port: '9200'
  hive:
    enabled: true
    metastore_host: localhost
    metastore_port: '9083'
  iceberg:
    enabled: true
    rest_host: localhost
    rest_port: '8181'
    s3_access_key: access-key
    s3_endpoint: http://localhost:9000
    s3_region: us-east-1
    s3_secret_key: secret-key
  mariadb:
    enabled: false
    host: localhost
    password: ''
    port: '3306'
    user: root
  mysql:
    enabled: false
    host: localhost
    password: ''
    port: '3306'
    user: root
  pinot:
    enabled: false
    host: localhost
    port: '9000'
  postgres:
    database: postgres
    enabled: true
    host: host.docker.internal
    password: postgres
    port: '5432'
    user: postgres
  sqlserver:
    database: master
    enabled: false
    host: localhost
    password: ''
    port: '1433'
    user: sa
  tpch:
    column_naming: SIMPLIFIED
    enabled: true
cluster1:
  container_name: trino1
  port: 8001
  version: '473'
cluster2:
  container_name: trino2
  port: 8002
  version: '474'
docker:
  auto_pull_images: false
  socket_path: ''
  timeout: 30
  trino_connect_host: localhost
