cluster1:
  version: '405'
  port: 8001
  container_name: trino1

cluster2:
  version: '406'
  port: 8002
  container_name: trino2

catalogs:
  hive:
    enabled: true
    metastore_host: localhost
    metastore_port: '9083'
  iceberg:
    enabled: true
    metastore_host: localhost
    metastore_port: '9083'
  delta-lake:
    enabled: false
    metastore_host: localhost
    metastore_port: '9083'
  mysql:
    enabled: true
    host: localhost
    port: '3306'
    user: root
    password: ''
  mariadb:
    enabled: false
    host: localhost
    port: '3306'
    user: root
    password: ''
  postgres:
    enabled: false
    host: localhost
    port: '5432'
    database: postgres
    user: postgres
    password: ''
  sqlserver:
    enabled: false
    host: localhost
    port: '1433'
    database: master
    user: sa
    password: ''
  db2:
    enabled: false
    host: localhost
    port: '50000'
    database: sample
    user: db2inst1
    password: ''
  clickhouse:
    enabled: false
    host: localhost
    port: '8123'
    user: default
    password: ''
  pinot:
    enabled: false
    host: localhost
    port: '9000'
  elasticsearch:
    enabled: true
    host: localhost
    port: '9200'
